name: Auto Renew Zampto

on:
  schedule:
    # Cấu hình tự động chạy mỗi 45 phút một lần để tối ưu hóa thời gian sống của Server
    - cron: '*/45 * * * *'
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
    - name: Kiểm tra mã nguồn
      uses: actions/checkout@v4

    - name: Cài đặt Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cài đặt thư viện và trình duyệt
      run: |
        pip install -r requirements.txt
        playwright install chromium

    - name: Chạy script gia hạn
      env:
        ZAMPTO_COOKIES: ${{ secrets.ZAMPTO_COOKIES }}
      run: python main.py

    - name: Tải ảnh màn hình lên GitHub nếu bị lỗi
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cloudflare-error-screenshot
        path: cloudflare_blocked.png
